project_id = "tjbiyyejofdpwybppxhv"

[api]
enabled = true
port = 54321

[functions.admin-invite-user]
verify_jwt = true

[functions.admin-update-user]
verify_jwt = true

[functions.admin-set-user-role]
verify_jwt = true

[functions.update-task]
verify_jwt = true

[functions.create-action]
verify_jwt = true

[functions.bau-weekly-import]
verify_jwt = true
